
INSERT INTO MerchantKeywordsCategories_Temp (Keyword, Title) VALUES
('Koru Souvenirs Welli','Personal Purchases'),
('Nz Red Cross','Personal Purchases'),
('Habib Barbers','Personal Purchases'),
('Kmart','Personal Purchases'),
('Twl','Personal Purchases'),
('San Jewellery','Personal Purchases'),
('Trade Me','Personal Purchases'),
('Post Shop','Personal Purchases'),
('Kathmandu','Personal Purchases'),
('Shoe Connection','Personal Purchases'),
('Macpac','Personal Purchases'),
('Pluralsight','Personal Purchases'),
('Whitcoulls','Personal Purchases'),
('Playstation','Personal Purchases'),
('Capital Mart','Personal Purchases'),
('The Nile','Personal Purchases'),
('Lovisa Wellington Nz','Personal Purchases'),
('Fishpond Co','Personal Purchases'),
('Mecca','Personal Purchases'),
('9554-****-****-1069','UNCATEGORIZED'),
('L Damaceno Da Si','UNCATEGORIZED'),
('E Ribeiro Da Silv','UNCATEGORIZED'),
('06-0294-0933649-01','UNCATEGORIZED'),
('Ewerton Nzhl','UNCATEGORIZED'),
('Asian Food Specialis','Groceries'),
('Butcher','Groceries'),
('Countdown','Groceries'),
('Countdown','Groceries'),
('Dairy','Groceries'),
('Duty Free','Groceries'),
('Food Store','Groceries'),
('Foodmart','Groceries'),
('Four Square','Groceries'),
('Gilmours','Groceries'),
('Green Grocer','Groceries'),
('Haere Mai','Groceries'),
('Havana Coffee','Groceries'),
('Liquor','Groceries'),
('Lyall Bay Mini','Groceries'),
('Mad Butcher','Groceries'),
('MERTON MINI','Groceries'),
('Merton Mini Mart','Groceries'),
('Moore Wilsons','Groceries'),
('New World','Groceries'),
('ON TRAYS LIMITED PETONE','Groceries'),
('Pak N Save','Groceries'),
('Preston','Groceries'),
('Super Save','Groceries'),
('Sovereign Amps','Insurance'),
('Aa Insurance Auckland Nzl','Insurance'),
('Fidelity Life Ass','Insurance'),
('Sovereign','Insurance'),
('Aa Insurance','Insurance'),
('Partners Life Limite','Insurance'),
('Nib','Insurance'),
('St Vincent De Paul','Others'),
('C Investments Limite','Others'),
('Transport','Others'),
('Azure','Others'),
('Station Gardens','Others'),
('Rainbow Bridges','Others'),
('Tt Services','Others'),
('Immigration','Others'),
('Embassy Of Brazil','Others'),
('Recycling Centre','Others'),
('Bike Barn','Others'),
('Jake Bicycle','House Purchases'),
('Bunnings','House Purchases'),
('The Warehouse','House Purchases'),
('The 123 Mart','House Purchases'),
('Brazilexpress','House Purchases'),
('Small Story','House Purchases'),
('Briscoes','House Purchases'),
('Mitre 10','House Purchases'),
('Brazilexpre','House Purchases'),
('Uncle Bill''S','House Purchases'),
('Harvey Norman','House Purchases'),
('Noel Leeming','House Purchases'),
('Dollar World','House Purchases'),
('Bbb Lyall Bay','House Purchases'),
('Lighting Direct','House Purchases'),
('Cwh Lambton','House Purchases'),
('Spotlight','House Purchases'),
('Farmers','House Purchases'),
('Trademe','House Purchases'),
('Lincraft ','House Purchases'),
('Bed Bath ','House Purchases'),
('Pb Technologies','House Purchases'),
('Color It','House Purchases'),
('Spotlight','House Purchases'),
('Amzn Mktp Us','House Purchases'),
('Fultons','Kylie Swimming'),
('Swim','Kylie Swimming'),
('Skinny','Mobile '),
('Vodafone','Mobile '),
('Skype','Mobile '),
('2Degrees','Mobile '),
('Pak N Save Fuel','Fuel'),
('Waitomo','Fuel'),
('Bp','Fuel'),
('Caltex','Fuel'),
('Mobil','Fuel'),
('Pak N Save Fuel','Fuel'),
('Challenge Moonshine','Fuel'),
('Kiwi Fuels','Fuel'),
('Z Mana','Fuel'),
('Mercury','Power'),
('Contact','Power'),
('Genesis','Power'),
('Wellington City ','Parking'),
('Pay My Park','Parking'),
('Wilson Parking','Parking'),
('Parking Services','Parking'),
('Online Payment - Thank You','Credit Card Payment'),
('9554-****-****-1081','Credit Card Payment'),
('Interest','Credit Card Interest'),
('Ccri Individual','Credit Card Interest'),
('Embassy Of Brazil','Immigration'),
('Dept. Of Immigration Southport Au','Immigration'),
('Immigration Nz Wellington Nz','Immigration'),
('Tt Services New Zealan','Immigration'),
('Nissan Finance','Car Maintenance'),
('Nz Transport Agency','Car Maintenance'),
('Boyle Kawasaki','Car Maintenance'),
('Gazley','Car Maintenance'),
('Repco','Car Maintenance'),
('That Car Place','Car Maintenance'),
('Everest Cafe Featherston Nzl','Coffee '),
('Lime Caffeteria Rotorua Nz','Coffee '),
('Essence Cafe Rotorua Nz','Coffee '),
('The Perching Parrot','Coffee '),
('The Coffee Club Poriru Porirua Nz','Coffee '),
('Starbucks 404 Wellington Nz','Coffee '),
('The Blue Belle Cafe','Coffee '),
('Muffin Break Lower Hutt Nz','Coffee '),
('Earnest','Coffee '),
('Floyd''S Cafe Wellington Nz','Coffee '),
('Beside The Shed','Coffee '),
('Enigma Cafe Wellington Nz','Coffee '),
('Floyd''S Cafe Wellington Nzl','Coffee '),
('Karaka Cafe','Coffee '),
('Mojo','Coffee '),
('The Hangar','Coffee '),
('Take My Money','Coffee '),
('New Chapter Wellington','Coffee '),
('Vanilla Cafe','Coffee '),
('Sfizio Espresso Bar','Coffee '),
('La Cloche','Coffee '),
('Buenos Aires Cafe','Coffee '),
('Cafe Medici','Coffee '),
('Supreme','Coffee '),
('Lukas','Dinning'),
('Pizzeria Napoli Wellington Nz','Dinning'),
('Mcdonalds Basin Reserv Wellington Nz','Dinning'),
('Gelissimo Wellington Nz Nz','Dinning'),
('Sushiya North City','Dinning'),
('Ngongotaha Fish Supp','Dinning'),
('Shyam Foodmarket','Dinning'),
('Sen Sushi','Dinning'),
('Tulsi','Dinning'),
('Abrakebabra','Dinning'),
('Spruce Goose Wellington Nz','Dinning'),
('Mac''S Brew Bar Wellington Nz','Dinning'),
('Mao & Co Porirua Nz','Dinning'),
('Tj Katsu And Udon','Dinning'),
('Mrs Higgins Cookies','Dinning'),
('Good Taste Thai Cuisin Wellington Nz','Dinning'),
('Mcdonalds Manners Stre Wellington Nz','Dinning'),
('Tommy Millions Wellington Nz','Dinning'),
('Sushi Maru','Dinning'),
('City Green Food And Porirua Nzl','Dinning'),
('Noodle Canteen','Dinning'),
('Mcdonalds','Dinning'),
('Bel Mondo Rongotai Nz','Dinning'),
('Fishermans Table','Dinning'),
('Tj Katsu And Udon','Dinning'),
('Great India Restaura','Dinning'),
('Silk Route Wellington Nz','Dinning'),
('Burger Liquor','Dinning'),
('Magiic Kitchen','Dinning'),
('The Oaks Satay Noodl','Dinning'),
('Sushi Bi Limited Wellington Nz','Dinning'),
('Town Country Food','Dinning'),
('Noodle Canteen','Dinning'),
('Kiwi Pies Bakery','Dinning'),
('Mcdonalds Taranaki S','Dinning'),
('J J Murphy & Co Wellington Nz','Dinning'),
('Mcdonalds Newtown Wellington Nz','Dinning'),
('Tj Katsu','Dinning'),
('The Spice Emporium Wellington Nz','Dinning'),
('Burger King','Dinning'),
('A1 Takeaways','Dinning'),
('Brown Owl Fisheries','Dinning'),
('Hey George Wellington Nz','Dinning'),
('Thai House Express Upper Hutt Nz','Dinning'),
('H G Yang','Dinning'),
('Maki Mono','Dinning'),
('Mcdonalds','Dinning'),
('Wainui Seafood','Dinning'),
('Kfc','Dinning'),
('Sunlong Restaurant','Dinning'),
('Siam Spoon Restaurant','Dinning'),
('Bay S Takeaway','Dinning'),
('Plaza Pizzeria','Dinning'),
('Fu Xian Takeaway','Dinning'),
('Auntie Mei Fast Food','Dinning'),
('Viet Food','Dinning'),
('Kl Malaysian Food St','Dinning'),
('Vietnamese Restauran','Dinning'),
('Fishermans Table','Dinning'),
('Dominos','Dinning'),
('Ox Bowl','Dinning'),
('Muffin Break','Dinning'),
('Magic Kitchen','Dinning'),
('The Cheesecake Shop','Dinning'),
('TRENTHAM MESS HALL','Dinning'),
('Busters Pizza','Dinning'),
('Tulsi Indian Cuisine','Dinning'),
('Domino''s','Dinning'),
('Shamiana Cuisine','Dinning'),
('A-Roy Thai Express','Dinning'),
('Jovans Kitchen','Dinning'),
('Heavens Woodfire Pizza','Dinning'),
('Aroy Thai','Dinning'),
('Yoshi Sushi & Bento','Dinning'),
('Merton St Fish & Chips','Dinning'),
('Ammu South Indian','Dinning'),
('The Lab Wellington','Dinning'),
('Silverspoon Rest','Dinning'),
('Boneface Brewery','Dinning'),
('Panhead Custom','Dinning'),
('Kyoto','Dinning'),
('Combustion Tkts','Dinning'),
('Guangzhou Cuisine','Dinning'),
('Bay''S Takeaway','Dinning'),
('Santo Churros','Dinning'),
('Neon','Entertainment '),
('Disney+','Entertainment '),
('Netflix','Entertainment '),
('Prime','Entertainment '),
('Wellington Cable Car Wellington Nzl','Entertainment '),
('Wellington Zoo Wellington Nzl','Entertainment '),
('Empire Cinema','Entertainment '),
('Tuatua Wellington Nz','Entertainment '),
('Newtown Bowling Club','Entertainment '),
('Wainui Pool','Entertainment '),
('Miramar rangers','Entertainment '),
('David Miramarrangers','Entertainment '),
('Daytona Raceway','Entertainment '),
('Amazon Music Unlimited','Entertainment '),
('Montereycinemaswelling','Entertainment '),
('Montereycinemas','Entertainment '),
('Frosty Spot','Entertainment '),
('Museum Of New Zealand','Entertainment '),
('Spotify','Entertainment '),
('Kilbirnie Rehab & Ph','Pharmacy'),
('After Hours Pharmacy','Pharmacy'),
('Unichem','Pharmacy'),
('Pharmacy','Pharmacy'),
('Bargain Chemist','Pharmacy'),
('Island Bay Med','Medical '),
('Afterhours Medical','Medical '),
('Simply Dental','Medical '),
('Horizon Radiology','Medical '),
('Capital Dental','Medical '),
('Silverstream Health','Medical '),
('Informphysio','Medical '),
('Inform Physiotherapy','Medical '),
('Real Transfer','Money Sent'),
('Wise','Money Sent'),
('Transferwise','Money Sent'),
('Wise','Money Received'),
('Transferwise','Money Received'),
('The Baby Factory','Kylie Clothes'),
('Anita''S Store','Kylie Clothes'),
('Southern Cross','Reimburse'),
('Nib','Reimburse'),
('Angela Rent','Mortgate'),
('Loan Payment','Mortgate'),
('Loan Interest','Mortgate'),
('Bigair Gymsports','Kylie Recreation'),
('Wgtn Regional Aquatic','Kylie Recreation'),
('Wis-Junglerama','Kylie Recreation'),
('H20 Xtream','Kylie Recreation'),
('Kilbirnie Rec','Kylie Recreation'),
('Chipmunks','Kylie Recreation'),
('Swim School','Kylie Recreation'),
('Rimutaka Gymsports','Kylie Recreation'),
('Gymnastics','Kylie Recreation'),
('Gym Class','Kylie Recreation'),
('Island Bay Childcare','Kylie School'),
('HAPPY DAYS','Kylie School'),
('Sacred Heart','Kylie School'),
('Thorndon School','Kylie School'),
('Nz Uniforms','Kylie School'),
('Sustainability Trust','Kylie School'),
('Kumon','Kylie School'),
('Trade Me Limited','Income'),
('Studylink','Income'),
('Host Familie','Income'),
('Civil Aviation','Income'),
('Partstrader Markets','Income'),
('Mito New Zealand','Income'),
('Two Degrees','Income'),
('2Degrees Mobile','Mobile '),
('Vodafone Fixed','Internet'),
('2Degrees','Internet'),
('Sportsdirect','Clothes & Shoes'),
('Hannahs Upper Hutt','Clothes & Shoes'),
('Savemart','Clothes & Shoes'),
('Pagani','Clothes & Shoes'),
('Unicef','Donations'),
('Cozy Cake Shop','Lunch'),
('Alaturka Kebab Pizza','Lunch'),
('Subway','Lunch'),
('Tj Sushi & Donburi','Lunch'),
('Souvlaki At Acropoli','Lunch'),
('Greenman','Lunch'),
('Tank','Lunch'),
('Lambton Food Market','Lunch'),
('The Fiddler Irish Bar','Lunch'),
('The Hudson','Lunch'),
('Leroys','Lunch'),
('One Sushi Courtenay','Lunch'),
('Art Craft Bakery','Lunch'),
('Fork And Brewer','Lunch'),
('Inland Revenue','IRD Tax'),
('Da Silveira E & L','Uncategorized Transfers'),
('Ewerton Coop','Uncategorized Transfers'),
('38-9019-0886316-00 Bill Payment Payment','Uncategorized Transfers'),
('38-9019-0886316-00 Bill Payment Savings','Uncategorized Transfers'),
('To: 88955757-1001','Uncategorized Transfers'),
('To: 88727730-1003','Uncategorized Transfers'),
('To: 88727730-1007','Uncategorized Transfers'),
('To: 88727730-1008','Uncategorized Transfers'),
('To: 88727730-1005','Uncategorized Transfers'),
('Joinery Hardware','Rental Houses'),
('Snapper Services','Transport'),
('Metlink','Transport'),
('Upper Hutt Cc','House Rates'),
('Ezi*Fitness Centres','Gym');




